name: Deploy to Azure App Service (Docker Hub)

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/flask-docker-demo:${{ github.sha }}
          docker build -t $IMAGE .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/flask-docker-demo:${{ github.sha }}
          docker push $IMAGE

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/flask-docker-demo:${{ github.sha }}
          az webapp config container set \
            --name ${{ secrets.APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name $IMAGE
          az webapp restart --name ${{ secrets.APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
